### ISSUE TITLE
Kotlin 2.1.0 changes IR Validation again

### ISSUE THREAD

**Issue by frett** [jeppeman/mockposable#32]
It looks like Kotlin changed the signature of the IrValidation functionality again, which breaks the current version of Mockposable for Kotlin 2.1.0.

```
e: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.backend.common.IrValidationContext.performBasicIrValidation$default(org.jetbrains.kotlin.backend.common.IrValidationContext, org.jetbrains.kotlin.ir.IrElement, org.jetbrains.kotlin.ir.IrBuiltIns, java.lang.String, boolean, boolean, boolean, int, java.lang.Object)'
	at com.jeppeman.mockposable.compiler.MockKIrGenerationExtension.generate$lambda$1(MockKIrGenerationExtension.kt:48)
	at org.jetbrains.kotlin.backend.common.IrValidatorKt.validateIr(IrValidator.kt:287)
	at com.jeppeman.mockposable.compiler.MockKIrGenerationExtension.generate(MockKIrGenerationExtension.kt:47)
	at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.applyIrGenerationExtensions(convertToIr.kt:472)
	at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.runActualizationPipeline(convertToIr.kt:241)
	at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.convertToIrAndActualize(convertToIr.kt:130)
```

**Comment by jeppeman** [comment]
Thanks for reporting @frett, `0.11` is available now.

**Comment by frett** [comment]
Cool, I'll give it a try on Monday when I'm back in the office

**Comment by frett** [comment]
The latest version works great, thanks for the quick update :)
